# Generated by Django 4.1.7 on 2023-03-15 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_path', models.TextField(max_length=255)),
                ('is_demo', models.BooleanField(default=False)),
                ('has_ruleset', models.BooleanField(default=False)),
                ('ruleset', models.FileField(upload_to='rulesets')),
                ('total_transcriptions', models.IntegerField(default=0)),
                ('total_audio_time', models.FloatField(default=0.0)),
                ('active_transcriptions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('project_path', models.TextField(max_length=255)),
                ('completed_project_file', models.FileField(upload_to='completed_projects')),
                ('total_transcriptions', models.IntegerField(default=0)),
                ('total_audio_time', models.FloatField(default=0.0)),
                ('active_transcriptions', models.IntegerField(default=0)),
                ('unexported_transcriptions', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='distribution.client')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('id_token', models.CharField(max_length=8)),
                ('active_transcriptions', models.IntegerField(default=50, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('total_transcription_time', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('time_taken', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='distribution.client')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='distribution.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
