# Generated by Django 4.1.7 on 2023-03-15 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.CharField(max_length=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('utterance', models.CharField(max_length=255)),
                ('time_to_complete', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('number_of_plays', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='distribution.client')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='distribution.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='distribution.project')),
            ],
            options={
                'get_latest_by': 'date_created',
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.CharField(max_length=8)),
                ('audio_file_name', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='audio')),
                ('audio_time', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('audio_rms', models.TextField()),
                ('utterance', models.CharField(max_length=255)),
                ('requests', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('has_been_exported', models.BooleanField(default=False)),
                ('date_last_requested', models.DateTimeField(null=True)),
                ('latest_revision_done_by_current_user', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='distribution.client')),
                ('job', models.ManyToManyField(related_name='transcriptions', to='distribution.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='distribution.project')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.CharField(max_length=8)),
                ('content', models.CharField(max_length=255)),
                ('tag', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='distribution.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='distribution.project')),
                ('revision', models.ManyToManyField(related_name='words', to='transcription.revision')),
                ('transcription', models.ManyToManyField(related_name='words', to='transcription.transcription')),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='transcription.transcription'),
        ),
        migrations.AddField(
            model_name='revision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
